# Site wide configuration

title: Sam Burden
locale: en_US
description: Assoc Prof in UW ECE
logo: sburdensq.png
search: true
url: http://localhost:4000
url: /sburden

# Jekyll configuration
#incremental: true

#permalink:   /:categories/:title/
permalink: /:year-:month-:day-:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Sam Burden
  avatar: sburdensq.png
  email: sburden@uw.edu
  github: sburden 
  linkedin: sam-burden 
  scholar: I9KPV_MAAAAJ 
  arxiv: burden_samuel
  orcid: 0000-0002-2705-7395
  twitter: SamBurdenUW
  #
  disqus-shortname:
  facebook: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
